version: '3.7'

services:
  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:80
  jaeger:
    image: jaegertracing/opentelemetry-all-in-one:latest
    ports:
      - 13133:13133
      - 16686:16686
      - 4317:55680
  brphistorieproxy:
    image: ${DOCKER_REGISTRY-}brphistorieproxy
    build:
      context: .
      dockerfile: src/BrpHistorieProxy/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      #- ASPNETCORE_URLS=https://+:5001;http://+:5000
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "5000:5000"
      #- "5001:5001"
    volumes:
      - ./src/config/BrpHistorieProxy/configuration:/app/configuration
  brphistoriestub:
    image: ${DOCKER_REGISTRY-}brphistoriestub
    build:
      context: .
      dockerfile: src/BrpHistorieStub/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      #- ASPNETCORE_URLS=https://+:5011;http://+:5010
      - ASPNETCORE_URLS=http://+:5010
    ports:
      - "5010:5010"
      #- "5011:5011"
    volumes:
      - ./src/config/BrpHistorieStub:/app/Data
