# flake8: noqa

# import all models into this package
# if you have many models here with many references from one model to another this may
# raise a RecursionError
# to avoid this, import only the models that you directly need like:
# from from openapi_client.model.pet import Pet
# or import this package, but before doing it, use:
# import sys
# sys.setrecursionlimit(n)

from openapi_client.model.aanduiding_bij_huisnummer_enum import AanduidingBijHuisnummerEnum
from openapi_client.model.aanduiding_bijzonder_nederlanderschap_enum import AanduidingBijzonderNederlanderschapEnum
from openapi_client.model.aangaan_huwelijk_partnerschap import AangaanHuwelijkPartnerschap
from openapi_client.model.aangaan_huwelijk_partnerschap_in_onderzoek import AangaanHuwelijkPartnerschapInOnderzoek
from openapi_client.model.adres import Adres
from openapi_client.model.bad_request_foutbericht import BadRequestFoutbericht
from openapi_client.model.bad_request_foutbericht_all_of import BadRequestFoutberichtAllOf
from openapi_client.model.datum_onvolledig import DatumOnvolledig
from openapi_client.model.foutbericht import Foutbericht
from openapi_client.model.geboorte import Geboorte
from openapi_client.model.geboorte_all_of import GeboorteAllOf
from openapi_client.model.geboorte_in_onderzoek import GeboorteInOnderzoek
from openapi_client.model.geboortedatum import Geboortedatum
from openapi_client.model.geslacht_enum import GeslachtEnum
from openapi_client.model.hal_collection_links import HalCollectionLinks
from openapi_client.model.hal_link import HalLink
from openapi_client.model.invalid_params import InvalidParams
from openapi_client.model.naam import Naam
from openapi_client.model.naam_in_onderzoek import NaamInOnderzoek
from openapi_client.model.nationaliteit import Nationaliteit
from openapi_client.model.nationaliteit_in_onderzoek import NationaliteitInOnderzoek
from openapi_client.model.nationaliteithistorie import Nationaliteithistorie
from openapi_client.model.nationaliteithistorie_all_of import NationaliteithistorieAllOf
from openapi_client.model.nationaliteithistorie_hal_collectie import NationaliteithistorieHalCollectie
from openapi_client.model.nationaliteithistorie_hal_collectie_embedded import NationaliteithistorieHalCollectieEmbedded
from openapi_client.model.ontbinding_huwelijk_in_onderzoek import OntbindingHuwelijkInOnderzoek
from openapi_client.model.ontbinding_huwelijk_partnerschap import OntbindingHuwelijkPartnerschap
from openapi_client.model.partner import Partner
from openapi_client.model.partner_in_onderzoek import PartnerInOnderzoek
from openapi_client.model.partnerhistorie import Partnerhistorie
from openapi_client.model.partnerhistorie_all_of import PartnerhistorieAllOf
from openapi_client.model.partnerhistorie_hal import PartnerhistorieHal
from openapi_client.model.partnerhistorie_hal_all_of import PartnerhistorieHalAllOf
from openapi_client.model.partnerhistorie_hal_collectie import PartnerhistorieHalCollectie
from openapi_client.model.partnerhistorie_hal_collectie_embedded import PartnerhistorieHalCollectieEmbedded
from openapi_client.model.partnerhistorie_links import PartnerhistorieLinks
from openapi_client.model.soort_adres_enum import SoortAdresEnum
from openapi_client.model.soort_verbintenis_enum import SoortVerbintenisEnum
from openapi_client.model.verblijfplaats import Verblijfplaats
from openapi_client.model.verblijfplaats_all_of import VerblijfplaatsAllOf
from openapi_client.model.verblijfplaats_in_onderzoek import VerblijfplaatsInOnderzoek
from openapi_client.model.verblijfplaatshistorie import Verblijfplaatshistorie
from openapi_client.model.verblijfplaatshistorie_all_of import VerblijfplaatshistorieAllOf
from openapi_client.model.verblijfplaatshistorie_hal import VerblijfplaatshistorieHal
from openapi_client.model.verblijfplaatshistorie_hal_all_of import VerblijfplaatshistorieHalAllOf
from openapi_client.model.verblijfplaatshistorie_hal_collectie import VerblijfplaatshistorieHalCollectie
from openapi_client.model.verblijfplaatshistorie_hal_collectie_embedded import VerblijfplaatshistorieHalCollectieEmbedded
from openapi_client.model.verblijfplaatshistorie_links import VerblijfplaatshistorieLinks
from openapi_client.model.verblijfstitel import Verblijfstitel
from openapi_client.model.verblijfstitel_in_onderzoek import VerblijfstitelInOnderzoek
from openapi_client.model.verblijfstitelhistorie import Verblijfstitelhistorie
from openapi_client.model.verblijfstitelhistorie_all_of import VerblijfstitelhistorieAllOf
from openapi_client.model.verblijfstitelhistorie_hal_collectie import VerblijfstitelhistorieHalCollectie
from openapi_client.model.verblijfstitelhistorie_hal_collectie_embedded import VerblijfstitelhistorieHalCollectieEmbedded
from openapi_client.model.waardetabel import Waardetabel
