/*
 * BRP historie bevragen
 * API voor het zoeken en raadplegen van historische verblijfplaatsen, partners, nationaliteiten en verblijfstitels uit de BRP (inclusief de RNI).  Zie de [Functionele documentatie](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-historie-bevragen/tree/v1.0.0/features) voor nadere toelichting. 
 *
 * The version of the OpenAPI document: 0.0.1 (develop)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.HalLink;

/**
 * PartnerhistorieLinks
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-01-14T15:42:47.439Z[Etc/UTC]")
public class PartnerhistorieLinks {
  public static final String SERIALIZED_NAME_INGESCHREVEN_PERSOON = "ingeschrevenPersoon";
  @SerializedName(SERIALIZED_NAME_INGESCHREVEN_PERSOON)
  private HalLink ingeschrevenPersoon;


  public PartnerhistorieLinks ingeschrevenPersoon(HalLink ingeschrevenPersoon) {
    
    this.ingeschrevenPersoon = ingeschrevenPersoon;
    return this;
  }

   /**
   * Get ingeschrevenPersoon
   * @return ingeschrevenPersoon
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public HalLink getIngeschrevenPersoon() {
    return ingeschrevenPersoon;
  }


  public void setIngeschrevenPersoon(HalLink ingeschrevenPersoon) {
    this.ingeschrevenPersoon = ingeschrevenPersoon;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PartnerhistorieLinks partnerhistorieLinks = (PartnerhistorieLinks) o;
    return Objects.equals(this.ingeschrevenPersoon, partnerhistorieLinks.ingeschrevenPersoon);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ingeschrevenPersoon);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PartnerhistorieLinks {\n");
    sb.append("    ingeschrevenPersoon: ").append(toIndentedString(ingeschrevenPersoon)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

