/* 
 * BRP historie bevragen
 *
 * API voor het zoeken en raadplegen van historische verblijfplaatsen, partners, nationaliteiten en verblijfstitels uit de BRP (inclusief de RNI).  Zie de [Functionele documentatie](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-historie-bevragen/tree/v1.0.0/features) voor nadere toelichting. 
 *
 * The version of the OpenAPI document: 0.0.1 (develop)
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// De aanduiding die wordt gebruikt voor adressen die geen straatnaam en huisnummeraanduidingen hebben * &#x60;tegenover&#x60; - to * &#x60;bij&#x60; - by 
    /// </summary>
    /// <value>De aanduiding die wordt gebruikt voor adressen die geen straatnaam en huisnummeraanduidingen hebben * &#x60;tegenover&#x60; - to * &#x60;bij&#x60; - by </value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum AanduidingBijHuisnummerEnum
    {
        /// <summary>
        /// Enum Tegenover for value: tegenover
        /// </summary>
        [EnumMember(Value = "tegenover")]
        Tegenover = 1,

        /// <summary>
        /// Enum Bij for value: bij
        /// </summary>
        [EnumMember(Value = "bij")]
        Bij = 2

    }

}
