/* 
 * BRP historie bevragen
 *
 * API voor het zoeken en raadplegen van historische verblijfplaatsen, partners, nationaliteiten en verblijfstitels uit de BRP (inclusief de RNI).  Zie de [Functionele documentatie](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-historie-bevragen/tree/v1.0.0/features) voor nadere toelichting. 
 *
 * The version of the OpenAPI document: 0.0.1 (develop)
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Gegevens over (historische) huwelijken en/of geregistreerd partnerschappen van de persoon. 
    /// </summary>
    [DataContract]
    public partial class PartnerhistorieAllOf :  IEquatable<PartnerhistorieAllOf>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PartnerhistorieAllOf" /> class.
        /// </summary>
        /// <param name="ontbindingHuwelijkPartnerschap">ontbindingHuwelijkPartnerschap.</param>
        public PartnerhistorieAllOf(OntbindingHuwelijkPartnerschap ontbindingHuwelijkPartnerschap = default(OntbindingHuwelijkPartnerschap))
        {
            this.OntbindingHuwelijkPartnerschap = ontbindingHuwelijkPartnerschap;
        }
        
        /// <summary>
        /// Gets or Sets OntbindingHuwelijkPartnerschap
        /// </summary>
        [DataMember(Name="ontbindingHuwelijkPartnerschap", EmitDefaultValue=false)]
        public OntbindingHuwelijkPartnerschap OntbindingHuwelijkPartnerschap { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PartnerhistorieAllOf {\n");
            sb.Append("  OntbindingHuwelijkPartnerschap: ").Append(OntbindingHuwelijkPartnerschap).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PartnerhistorieAllOf);
        }

        /// <summary>
        /// Returns true if PartnerhistorieAllOf instances are equal
        /// </summary>
        /// <param name="input">Instance of PartnerhistorieAllOf to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PartnerhistorieAllOf input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.OntbindingHuwelijkPartnerschap == input.OntbindingHuwelijkPartnerschap ||
                    (this.OntbindingHuwelijkPartnerschap != null &&
                    this.OntbindingHuwelijkPartnerschap.Equals(input.OntbindingHuwelijkPartnerschap))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.OntbindingHuwelijkPartnerschap != null)
                    hashCode = hashCode * 59 + this.OntbindingHuwelijkPartnerschap.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
