openapi: 3.0.3
info:
  title: Persoon definities
  version: 2.0.0
  contact: {}
paths: {}
components:
  schemas:
    GemeenteVanInschrijving:
      description: |
        Een code die aangeeft in welke gemeente de persoon woont, of de laatste gemeente waar de persoon heeft gewoond, of de gemeente waar de persoon voor het eerst is ingeschreven.
      type: string
      pattern: ^[0-9]{4}$
      example: "0518"
    GbaPersoonBeperkt:
      type: object
      properties:
        burgerservicenummer:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/persoon.yaml#/components/schemas/Burgerservicenummer'
        geboorte:
          $ref: 'geboorte.yaml#/components/schemas/GbaGeboorteBeperkt'
        geheimhoudingPersoonsgegevens:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/persoon.yaml#/components/schemas/GbaGeheimhoudingPersoonsgegevens'
        geslacht:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/common.yaml#/components/schemas/Waardetabel'
        naam:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/naam.yaml#/components/schemas/GbaNaamBasis'
        opschortingBijhouding:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/opschortingbijhouding.yaml#/components/schemas/OpschortingBijhoudingBasis'
        overlijden:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/overlijden.yaml#/components/schemas/GbaOverlijdenBasis'
        gemeenteVanInschrijving:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/common.yaml#/components/schemas/Waardetabel'
        verblijfplaats:
          $ref: 'verblijfplaats.yaml#/components/schemas/GbaVerblijfplaatsBeperkt'
    PersoonBeperkt:
      type: object
      description: |
        * **geslachtsaanduiding** - Wordt gevuld op basis van de waarden die voorkomen in de tabel 'Geslacht' uit de Haal-Centraal-BRP-tabellen-bevragen API.
      properties:
        burgerservicenummer:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/persoon.yaml#/components/schemas/Burgerservicenummer'
        geboorte:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/geboorte.yaml#/components/schemas/GeboorteBeperkt'
        geheimhoudingPersoonsgegevens:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/persoon.yaml#/components/schemas/GeheimhoudingPersoonsgegevens'
        geslacht:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/common.yaml#/components/schemas/Waardetabel'
        leeftijd:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/persoon.yaml#/components/schemas/Leeftijd'
        naam:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/naam.yaml#/components/schemas/NaamBasis'
        opschortingBijhouding:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/opschortingbijhouding.yaml#/components/schemas/OpschortingBijhoudingBasis'
        overlijden:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/overlijden.yaml#/components/schemas/OverlijdenBasis'
        verblijfplaats:
          $ref: 'verblijfplaats.yaml#/components/schemas/AbstractVerblijfplaatsBeperkt'
        adressering:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/adressering.yaml#/components/schemas/AdresseringBeperkt'
    GbaPersoon:
      type: object
      properties:
        aNummer:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/persoon.yaml#/components/schemas/ANummer'
        burgerservicenummer:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/persoon.yaml#/components/schemas/Burgerservicenummer'
        datumEersteInschrijvingGBA:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/datum.yaml#/components/schemas/GbaDatum'
        geheimhoudingPersoonsgegevens:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/persoon.yaml#/components/schemas/GbaGeheimhoudingPersoonsgegevens'
        geslacht:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/common.yaml#/components/schemas/Waardetabel'
        inOnderzoek:
          $ref: 'gba-inonderzoek.yaml#/components/schemas/GbaInOnderzoek'
        uitsluitingKiesrecht:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/kiesrecht.yaml#/components/schemas/GbaUitsluitingKiesrecht'
        europeesKiesrecht:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/kiesrecht.yaml#/components/schemas/GbaEuropeesKiesrecht'
        naam:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/naam.yaml#/components/schemas/GbaNaamPersoon'
        nationaliteiten:
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/nationaliteit.yaml#/components/schemas/GbaNationaliteit'
        geboorte:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/geboorte.yaml#/components/schemas/GbaGeboorte'
        opschortingBijhouding:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/opschortingbijhouding.yaml#/components/schemas/GbaOpschortingBijhouding'
        overlijden:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/overlijden.yaml#/components/schemas/GbaOverlijden'
        verblijfplaats:
          $ref: 'verblijfplaats.yaml#/components/schemas/GbaVerblijfplaats'
        immigratie:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/immigratie.yaml#/components/schemas/GbaImmigratie'
        gemeenteVanInschrijving:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/common.yaml#/components/schemas/Waardetabel'
        datumInschrijvingInGemeente:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/datum.yaml#/components/schemas/GbaDatum'
        indicatieCurateleRegister:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/persoon.yaml#/components/schemas/IndicatieCurateleRegister'
        indicatieGezagMinderjarige:
          $ref: 'common.yaml#/components/schemas/Waardetabel'
        verblijfstitel:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/verblijfstitel.yaml#/components/schemas/GbaVerblijfstitel'
        reisdocumentnummers:
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/persoon.yaml#/components/schemas/Reisdocumentnummer'
        kinderen:
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/kind.yaml#/components/schemas/GbaKind'
        ouders:
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/ouder.yaml#/components/schemas/GbaOuder'
        partners:
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/partner.yaml#/components/schemas/GbaPartner'
    Persoon:
      type: object
      description: |
        * **geslachtsaanduiding** - Wordt gevuld op basis van de waarden die voorkomen in de tabel 'Geslacht' uit de Haal-Centraal-BRP-tabellen-bevragen API.
      properties:
        aNummer:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/persoon.yaml#/components/schemas/ANummer'
        burgerservicenummer:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/persoon.yaml#/components/schemas/Burgerservicenummer'
        datumEersteInschrijvingGBA:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/datum.yaml#/components/schemas/AbstractDatum'
        geheimhoudingPersoonsgegevens:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/persoon.yaml#/components/schemas/GeheimhoudingPersoonsgegevens'
        geslacht:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/common.yaml#/components/schemas/Waardetabel'
        inOnderzoek:
          $ref: '#/components/schemas/PersoonInOnderzoek'
        uitsluitingKiesrecht:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/kiesrecht.yaml#/components/schemas/UitsluitingKiesrecht'
        europeesKiesrecht:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/kiesrecht.yaml#/components/schemas/EuropeesKiesrecht'
        leeftijd:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/persoon.yaml#/components/schemas/Leeftijd'
        naam:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/naam.yaml#/components/schemas/NaamPersoon'
        nationaliteiten:
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/nationaliteit.yaml#/components/schemas/AbstractNationaliteit'
        geboorte:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/geboorte.yaml#/components/schemas/Geboorte'
        opschortingBijhouding:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/opschortingbijhouding.yaml#/components/schemas/OpschortingBijhouding'
        overlijden:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/overlijden.yaml#/components/schemas/Overlijden'
        verblijfplaats:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/verblijfplaats.yaml#/components/schemas/AbstractVerblijfplaats'
        immigratie:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/immigratie.yaml#/components/schemas/Immigratie'
        gemeenteVanInschrijving:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/common.yaml#/components/schemas/Waardetabel'
        datumInschrijvingInGemeente:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/datum.yaml#/components/schemas/AbstractDatum'
        adressering:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/adressering.yaml#/components/schemas/Adressering'
        indicatieCurateleRegister:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/persoon.yaml#/components/schemas/IndicatieCurateleRegister'
        indicatieGezagMinderjarige:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/common.yaml#/components/schemas/Waardetabel'
        verblijfstitel:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/verblijfstitel.yaml#/components/schemas/Verblijfstitel'
        reisdocumentnummers:
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/persoon.yaml#/components/schemas/Reisdocumentnummer'
        kinderen:
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/kind.yaml#/components/schemas/AbstractKind'
        ouders:
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/ouder.yaml#/components/schemas/AbstractOuder'
        partners:
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/partner.yaml#/components/schemas/AbstractPartner'
    PersoonInOnderzoek:
      description: |
        Geeft aan welke gegevens van de persoon in onderzoek zijn. Zie de [functionele specificaties](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/v1.1.0/features/in_onderzoek.feature).
      allOf:
        - $ref: '#/components/schemas/InOnderzoek'
        - type: object
          properties:
            burgerservicenummer:
              type: boolean
            geslacht:
              type: boolean
            leeftijd:
              type: boolean
            gemeenteVanInschrijving:
              type: boolean
            datumInschrijvingInGemeente:
              type: boolean
            indicatieCurateleRegister:
              type: boolean
            indicatieGezagMinderjarige:
              type: boolean
    InOnderzoek:
      type: object
      properties:
        datumIngangOnderzoek:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/datum.yaml#/components/schemas/AbstractDatum'
        datumTot:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/develop/specificatie/datum.yaml#/components/schemas/AbstractDatum'
