baseurl: "/Haal-Centraal-BRP-historie-bevragen"
apiname: "BRP Verblijfplaatshistorie"
url: "http://localhost:4000"
proefProxyUrl: https://demo-omgeving.haalcentraal.nl
onboardingUrl: https://github.com/BRP-API/Haal-Centraal-BRP-bevragen/blob/master/docs/240610%20deelname%20BRP%20API%20v2.6.ppsx
proefProxyUrl: https://demo-omgeving.haalcentraal.nl

PO-email: cathy.dingemanse@rvig.nl
CZ-email: melvin.lee@rvig.nl
Tester-email: frank.samwel@rvig.nl

apiname: "BRP API Verblijfplaatshistorie"

# M.b.v. de optionele variabele 'logo' kan een ander logo dan het VNG logo in de rechterbovenhoek geplaatst worden.
# Het betreffende bestand zal dan wel in de folder '\assets\img' van het remote the 'VNG-Realisatie/jekyll-theme-haal-centraal' moeten worden geplaatst.
# Met de variabele 'organisation-url' kan de link onder het logo worden bepaald.
logo: "BZK_RIG_Logo_online_ex_pos_nl.png"
organisation-url: "http://www.rvig.nl"
# nav is t.b.v. generatie side-navigation menu.
# Een 'title' zonder path of url genereert slechts een kopje.
# 'path' vormt tezamen met de baseurl de url waarmee de 'href' wordt gevuld. 
# Indien een 'url' voorradig dan wordt daarmee de 'href' gevuld en dient het path slechts om te bepalen welke link active is.
# 'target: blank' zorgt er voor dat de link in een nieuw tabblad wordt geöpend.
nav:
  - title: BRP Verblijfplaatshistorie 
    subnav:
      - title: Main
        path: /
#      - title: Goals canvas
#        path: /goals-canvas
      - title: Getting started
        path: /getting-started
      - title: User stories
        path: /user-stories
      - title: User stories  (afgeschermd)
        url: https://gitlab.com/vng-realisatie/haal-centraal-brp-afgeschermd/-/issues?label_name%5B%5D=historie
        path: /user-stories-afgeschermd
        target: blank
      - title: Specificaties (redoc)
        path: /redoc
      - title: Features
        path: /features-overzicht
plugins:
  - jekyll-redirect-from
  - jekyll-remote-theme

remote_theme: VNG-Realisatie/jekyll-theme-haal-centraal

github: BRP-API/Haal-Centraal-BRP-historie-bevragen

theme: jekyll-theme-time-machine

project_name: /Haal-Centraal-BRP-historie-bevragen
